name: bact_analysis
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - altair=6.0.0
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.2
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.2
  - aws-sdk-cpp=1.11.606
  - backports.zstd=1.2.0
  - blinker=1.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cachetools=6.2.2
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - gitdb=4.0.12
  - gitpython=3.1.45
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.11
  - importlib-metadata=8.7.0
  - jinja2=3.1.6
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libdeflate=1.25
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libparquet=22.0.0
  - libpng=1.6.53
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.2
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - mkl=2025.3.0
  - narwhals=2.13.0
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openssl=3.6.0
  - orc=2.2.1
  - packaging=25.0
  - pandas=2.3.3
  - pillow=12.0.0
  - pip=25.3
  - protobuf=6.31.1
  - pthread-stubs=0.4
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pydeck=0.9.1
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.3
  - re2=2025.11.05
  - referencing=0.37.0
  - requests=2.32.5
  - rpds-py=0.30.0
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.2
  - streamlit=1.52.1
  - tbb=2022.3.0
  - tenacity=9.1.2
  - tk=8.6.13
  - toml=0.10.2
  - tornado=6.5.2
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - urllib3=2.6.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - watchdog=6.0.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib-ng=2.3.2
  - zstd=1.5.7